apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jxl-e2e-gc
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: e2e-gc
            release: jx
        spec:
          containers:
          - args:
            - step
            - e2e
            - gc
            - --project-id=jenkins-x-labs-bdd
            - --batch-mode
            command:
            - jx
            env:
            - name: JX_LOG_FORMAT
              value: json
            image: gcr.io/jenkinsxio-labs/jxl:{{ .Values.jxl.version }}
            imagePullPolicy: IfNotPresent
            name: e2e-gc
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          serviceAccountName: tekton-bot
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0/10 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
