apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  name: jx-versions-scheduler
spec:
  plugins:
    entries:
      - label
  postsubmits:
    replace: true
    entries:
    - agent: tekton
      branches:
        entries:
        - master
      name: release
      context: ""
  presubmits:
    replace: true
    entries:
    - agent: tekton
      alwaysRun: false
      context: boot-helm3
      name: boot-helm3
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test boot-helm3
      trigger: (?m)^/test( all| boot-helm3),?(s+|$)
    - agent: tekton
      alwaysRun: false
      context: boot-helm3-mc
      name: boot-helm3-mc
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test boot-helm3-mc
      trigger: (?m)^/test( all| boot-helm3-mc),?(s+|$)

