apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  name: jx-versions-scheduler
spec:
  plugins:
    entries:
      - label
  postsubmits:
    replace: true
    entries:
    - agent: tekton
      branches:
        entries:
        - master
      name: release
      context: ""
  presubmits:
    replace: true
    entries:
    - agent: tekton
      alwaysRun: true
      context: gke
      name: gke
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test gke
      trigger: (?m)^/test( all| gke),?(s+|$)
    - agent: tekton
      alwaysRun: false
      context: gsm
      name: gsm
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test gsm
      trigger: (?m)^/test( all| gsm),?(s+|$)
    - agent: tekton
      alwaysRun: false
      context: kube
      name: kube
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test kube
      trigger: (?m)^/test( all| kube),?(s+|$)
    - agent: tekton
      alwaysRun: false
      context: mc
      name: mc
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test mc
      trigger: (?m)^/test( all| mc),?(s+|$)
    - agent: tekton
      alwaysRun: false
      context: storage
      name: storage
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test storage
      trigger: (?m)^/test( all| storage),?(s+|$)
    - agent: tekton
      alwaysRun: false
      context: terraform
      name: terraform
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test terraform
      trigger: (?m)^/test( all| terraform),?(s+|$)
    - agent: tekton
      alwaysRun: false
      context: tls
      name: tls
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test tls
      trigger: (?m)^/test( all| tls),?(s+|$)
    - agent: tekton
      alwaysRun: true
      context: vault
      name: vault
      queries:
      - labels:
          entries:
          - approved
          - lgtm
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
      - labels:
          entries:
            - updatebot
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
            - needs-security-review
      report: true
      rerunCommand: /test vault
      trigger: (?m)^/test( all| vault),?(s+|$)

