apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jx-version-stream-update
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: jx-version-stream-update
            release: jx
        spec:
          containers:
          - args:
            - step
            - create
            - pr
            - versions
            - --filter=*
            - --images
            - --excludes=jetstack/cert-manager
            - --excludes=bitnami/external-dns
            - --excludes=external-secrets/kubernetes-external-secrets
            - --excludes=flagger/flagger
            - --batch-mode
            command:
            - jx
            env:
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: PIPELINE_KIND
              value: release
            image: gcr.io/jenkinsxio-labs/jxl:{{ .Values.jxl.version }}
            imagePullPolicy: IfNotPresent
            name: jx-version-stream-update
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: tekton-bot
  schedule: 0 */12 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
